#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# Authors:	Ricardo and Elicarlos - checkmk@lynxmind.com
# URL:	https://github.com/LynxmindRepo/lynxmind-cloudflare-checkmk-plugin
# License: GNU General Public License v2

import sys
import asyncio
from cmk_addons.plugins.cloud_flare.special_agents.cloudflare import main as cloudflare_main

if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(cloudflare_main()))
    except KeyboardInterrupt:
        sys.exit(1)

